"""Decide what goes in the map: the spine, the noise, and what will not fit.

This is where recce earns or loses its keep. Producing the call graph is
mechanical, and a tool that dumps all of it is no better than `pyan`. The
filtering is the product, so the choices here are the ones to argue with:

- **What counts as trivial.** A one-line wrapper given its own row costs the
  same vertical space as the function doing the work, so it is collapsed. The
  test is structural (statement count, no branching, nothing called), not a
  guess about importance.
- **What earns a star.** Branch count is the strongest available proxy for
  "the interesting logic" — the reader is looking for the function that holds
  the decisions. Size, fan-in and fan-out break ties.
- **When to split.** The budget is a real constraint, not a suggestion, and a
  map that quietly runs to three screens has failed at its one job. So the tree
  is pruned down a fixed ladder, and when the bottom of that ladder still does
  not fit, the map splits instead of shrinking further.

Nothing here reads a function body's meaning. `Func.note` stays empty; that is
the slot a model fills in later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Set, Tuple

from .graph import Graph, external_display
from .model import EXTERNAL, KEEP, PROJECT, SKIM, SPINE, TRIVIAL, Func, Project

# Decorators that mean "a framework calls this", so the function is a way in
# even though nothing in the project calls it.
_ENTRY_DECORATORS = (
    'route',
    'get',
    'post',
    'put',
    'patch',
    'delete',
    'command',
    'group',
    'task',
    'callback',
    'main',
    'handler',
    'entry_point',
)

# Decorators that mean the opposite: the function is machinery, and starting a
# read there would be a wrong turn.
_NON_ENTRY_DECORATORS = ('fixture', 'property', 'cached_property', 'setter', 'deleter')

# The pruning ladder, tried in order until the map fits its budget. Written
# out rather than generated by nested loops so the order of concessions is
# something you can read and argue with, which is the whole point of it.
#
# The order says what recce believes is worth least. Notes go before rows,
# because a row the reader cannot see is a call they will not know about,
# while a missing note only costs them a sentence they can get by opening the
# file. Depth goes before breadth for the same reason: a reader four levels
# down has already left the flow the map is describing.
_DEPTH_LADDER = (6, 5, 4, 3)


def _rungs():
    """Budget concessions, cheapest first."""
    for notes in ('all', 'spine', 'none'):
        for drop_skim in (False, True):
            for depth_cap in _DEPTH_LADDER:
                for external_depth in (99, 2):
                    yield {
                        'depth_cap': depth_cap,
                        'drop_skim': drop_skim,
                        'external_depth': external_depth,
                        'notes': notes,
                    }


@dataclass
class Node:
    """One row in a rendered tree.

    A row is either a project function (`func` set) or an external call
    (`bracket` set), never both. The collapsed-helpers row is a third case with
    neither, carrying its text in `label`.
    """

    label: str
    func: Optional[Func] = None
    ret: Optional[str] = None
    marker: str = ''
    bracket: Optional[str] = None
    children: List[Node] = field(default_factory=list)
    repeat: bool = False
    note: Optional[str] = None

    def line_count(self) -> int:
        # A note is a line, and the budget is about lines. Counting the row but
        # not its note is how a map with notes turned on quietly runs a third
        # longer than the budget it claims to keep.
        return (
            1
            + (1 if self.note else 0)
            + sum(child.line_count() for child in self.children)
        )


@dataclass
class Block:
    """One `##` section of the finished map: a heading and its own tree."""

    title: str
    purpose: Optional[str]
    roots: List[Node] = field(default_factory=list)

    def line_count(self) -> int:
        return sum(root.line_count() for root in self.roots)


@dataclass
class Plan:
    """Everything the renderer needs, with every judgement already made."""

    blocks: List[Block] = field(default_factory=list)
    strategy: str = 'single'  # 'single' | 'module' | 'entry'
    spine: List[Func] = field(default_factory=list)
    entries: List[Func] = field(default_factory=list)
    omitted_modules: int = 0


def annotate(project: Project, graph: Graph) -> List[Func]:
    """Score every function and assign it a role. Returns the entry points."""
    funcs = project.funcs()
    entries = _entry_points(project, graph)
    _assign_depth(funcs, graph, entries)
    _score(funcs, graph)
    _assign_roles(funcs, graph, entries)
    return entries


def _entry_points(project: Project, graph: Graph) -> List[Func]:
    """Find the ways in, best evidence first.

    A `__main__` guard is a fact about the file rather than an inference, so it
    outranks everything. A framework decorator is nearly as good. Only when
    neither exists do we fall back to graph shape, where "nothing in the
    project calls it" is suggestive but routinely wrong — an unused helper
    looks identical to an entry point from the graph alone.
    """
    by_id = project.by_id()
    ranked: List[Tuple[int, str, Func]] = []
    seen: Set[str] = set()

    def offer(func: Optional[Func], rank: int) -> None:
        if func is not None and func.node_id not in seen:
            seen.add(func.node_id)
            ranked.append((rank, func.node_id, func))

    for module in project.modules.values():
        for target in graph.entry_calls.get(module.name, []):
            offer(by_id.get(target), 0)

    for func in project.funcs():
        decorators = [d.split('.')[-1] for d in func.decorators]
        if any(d in _NON_ENTRY_DECORATORS for d in decorators):
            continue
        if any(d in _ENTRY_DECORATORS for d in decorators):
            offer(func, 1)
        elif func.name == 'main' and not func.is_method:
            offer(func, 2)

    for func in project.funcs():
        if func.fan_in or not func.is_public or func.name.startswith('test_'):
            continue
        if any(d.split('.')[-1] in _NON_ENTRY_DECORATORS for d in func.decorators):
            continue
        # A method with no callers is only a way in if the class is a real
        # object rather than a record; a dataclass field accessor is not.
        offer(func, 3 if not func.is_method else 4)

    ranked.sort(key=lambda item: (item[0], -item[2].n_branches, item[1]))
    return [func for _, _, func in ranked]


def _assign_depth(funcs: Sequence[Func], graph: Graph, entries: Sequence[Func]) -> None:
    """Breadth-first call depth from the nearest entry point."""
    for func in funcs:
        func.depth = None
    frontier = [(func.node_id, 0) for func in entries]
    by_id = {func.node_id: func for func in funcs}
    while frontier:
        node_id, depth = frontier.pop(0)
        func = by_id.get(node_id)
        if func is None or (func.depth is not None and func.depth <= depth):
            continue
        func.depth = depth
        for callee in graph.callees(node_id):
            frontier.append((callee, depth + 1))


def _norm(values: Sequence[float]) -> Dict[int, float]:
    """Min-max normalise, treating an all-equal set as all-zero."""
    if not values:
        return {}
    low, high = min(values), max(values)
    span = high - low
    return {i: ((v - low) / span if span else 0.0) for i, v in enumerate(values)}


def _score(funcs: Sequence[Func], graph: Graph) -> None:
    """Rank functions by how likely they are to be worth reading first.

    The weights say branching matters most. That is the claim this scoring
    rests on, and it holds up because a reader opening unfamiliar code is
    looking for where the decisions live — a long function with no branches is
    usually a table or a builder, and skimming it loses nothing.
    """
    if not funcs:
        return
    branches = _norm([_effective_branches(f) for f in funcs])
    sizes = _norm([f.loc for f in funcs])
    fan_ins = _norm([f.fan_in for f in funcs])
    fan_outs = _norm([len(graph.callees(f.node_id)) for f in funcs])
    for index, func in enumerate(funcs):
        func.score = (
            (
                0.45 * branches[index]
                + 0.25 * sizes[index]
                + 0.15 * fan_ins[index]
                + 0.15 * fan_outs[index]
            )
            * _presentation_factor(func)
            * _constructor_factor(func)
        )


# A helper this size is met inside its caller and not navigated to. The bounds
# were set against the three helpers the code-map skill's fixtures name as
# trivial — `_parse_args`, `_parse_bytes`, `_human_bytes` — the largest of
# which is six lines with a loop and a branch in it.
_TRIVIAL_LOC = 8
_TRIVIAL_BRANCHES = 2


# Dunders that are wiring rather than behaviour. A constructor branches once
# per optional argument, which is the same shape as branching once per case in
# a dispatch table and means something entirely different.
_WIRING_METHODS = frozenset(
    {'__init__', '__new__', '__post_init__', '__repr__', '__str__', '__eq__'}
)


def _effective_branches(func: Func) -> float:
    """Branch count with conditional expressions worth half a decision each.

    `value if value is not None else default` is a defaulting idiom, not a
    fork the reader has to hold in their head, and a constructor with six of
    them is doing less thinking than a loop with two real branches. Counting
    them equally is what let `httpx`'s `Client.__init__` outscore
    `Client.send`.

    Half rather than zero: a ternary inside a comprehension really is a
    decision, and the point is to stop them dominating, not to stop them
    counting.
    """
    return func.n_branches - 0.5 * func.n_ternaries


def _constructor_factor(func: Func) -> float:
    """Discount setup methods, which branch a lot and decide little.

    Found on `httpx`: `Client.__init__` and `AsyncClient.__init__` outscored
    every other method in `_client.py` and took the whole block's line budget,
    leaving `Client.send` — the function the module exists for — off the map.
    Argument wrangling looks like logic to a branch counter.

    A discount rather than a veto, because a constructor that really does the
    work should still be able to win.
    """
    return 0.6 if func.name in _WIRING_METHODS else 1.0


def _presentation_factor(func: Func) -> float:
    """Discount functions that are building output rather than deciding things.

    A report writer and an aggregator have the same shape to a branch counter:
    both are a loop over a collection with a couple of conditionals. The
    difference is what is inside the loop, and string literals are the cheapest
    reliable tell — roughly one per line means the body is text, not logic.

    This is a discount and not a veto on purpose. A formatter with genuinely
    intricate branching still outscores a plain one, which is the right
    outcome; it just no longer outscores the code that computes what it prints.
    """
    if func.loc < 4 or func.n_strings < 3:
        return 1.0
    density = func.n_strings / float(func.loc)
    return 0.65 if density >= 0.5 else 0.8


def _is_trivial(func: Func, graph: Graph) -> bool:
    """Whether a function is too small to deserve a row of its own.

    The test is structural, and the load-bearing part is that it is *not* the
    branch count. An earlier version required zero branches and let a six-line
    byte formatter with a loop in it through, because a `for` over four unit
    suffixes counts the same as a `for` over a million records.

    What separates a helper from a step is three things together:

    - it is a leaf in the project, calling nothing of ours
    - it is short, under `_TRIVIAL_LOC` lines
    - it is either private, or too small to hide anything at two statements

    All three have to hold. A public function is somebody's interface even when
    it is short, and a function that calls into the project is a step in the
    flow whatever its size, because the reader following that flow has to pass
    through it.
    """
    if graph.callees(func.node_id):
        return False
    if func.n_branches > _TRIVIAL_BRANCHES:
        return False
    if func.loc > _TRIVIAL_LOC:
        return False
    return not func.is_public or func.n_stmts <= 2


def _assign_roles(funcs: Sequence[Func], graph: Graph, entries: Sequence[Func]) -> None:
    """Write `role` onto every function: spine, skim, trivial, or plain."""
    entry_ids = {func.node_id for func in entries}
    for func in funcs:
        if func.node_id not in entry_ids and _is_trivial(func, graph):
            func.role = TRIVIAL
        else:
            func.role = KEEP

    kept = [f for f in funcs if f.role != TRIVIAL]
    if kept:
        cutoff = sorted(f.score for f in kept)[max(len(kept) // 3 - 1, 0)]
        for func in kept:
            if (
                func.node_id not in entry_ids
                and func.n_branches == 0
                and func.score <= cutoff
            ):
                func.role = SKIM

    for func in _pick_spine(funcs, entries):
        func.role = SPINE


def _pick_spine(funcs: Sequence[Func], entries: Sequence[Func]) -> List[Func]:
    """Choose the one to three functions to star.

    The first entry point is always one of them: it is where the reader starts
    whatever else is true, and a map whose star is buried three levels down
    tells them to start in the middle. The rest go to the highest-scoring
    functions that are actually reachable, because starring dead code is worse
    than starring nothing.
    """
    chosen: List[Func] = []
    if entries:
        chosen.append(entries[0])
    reachable = [
        f
        for f in funcs
        if f.depth is not None and f.role != TRIVIAL and f not in chosen
    ]
    reachable.sort(key=lambda f: (-f.score, f.module, f.lineno))
    for func in reachable:
        if len(chosen) >= 3:
            break
        # A second star next door to the first says less than one further out.
        if func.n_branches == 0 and len(chosen) >= 2:
            continue
        chosen.append(func)
    if not chosen and funcs:
        chosen = [max(funcs, key=lambda f: f.score)]
    return chosen[:3]


def _module_order(project: Project) -> List[str]:
    """Project modules, leaves first, so a reader meets callees before callers.

    Kahn's algorithm with a deterministic tie-break. Import cycles are common
    enough in real code that a `CycleError` would be a bad outcome, so a cycle
    is broken by taking the alphabetically first remaining module and carrying
    on. The order degrades; nothing fails.
    """
    names = sorted(project.modules)
    deps: Dict[str, Set[str]] = {name: set() for name in names}
    for name, module in project.modules.items():
        for bound in module.imports.values():
            for other in names:
                if other != name and (bound == other or bound.startswith(other + '.')):
                    deps[name].add(other)

    ordered: List[str] = []
    remaining = set(names)
    while remaining:
        ready = sorted(n for n in remaining if not (deps[n] & remaining))
        if not ready:
            ready = [sorted(remaining)[0]]
        for name in ready:
            ordered.append(name)
            remaining.discard(name)
    return ordered


def _build_tree(
    root: Func,
    project: Project,
    graph: Graph,
    depth_cap: int = 6,
    emitted: Optional[Set[str]] = None,
    members: Optional[Set[str]] = None,
    drop_skim: bool = False,
    external_depth: int = 99,
    notes: str = 'all',
) -> Node:
    """Expand one entry point into a row tree, honouring the current budget."""
    by_id = project.by_id()
    if emitted is None:
        emitted = set()

    def expand(func: Func, depth: int, path: Set[str]) -> Node:
        node = Node(
            label=func.qualname,
            func=func,
            ret=func.returns,
            marker=_marker_for(func),
            note=_note_for(func, notes),
        )
        emitted.add(func.node_id)
        if depth >= depth_cap or func.node_id in path:
            return node

        trivial: List[str] = []
        trivial_labels: List[str] = []
        for call in func.calls:
            if call.kind == PROJECT and call.target:
                callee = by_id.get(call.target)
                if callee is None or callee.node_id == func.node_id:
                    continue
                if members is not None and callee.node_id not in members:
                    # In a split map the edge still happened, and saying so is
                    # the point of splitting by module rather than by accident.
                    # It becomes a reference leaf — named the way the calling
                    # file writes it — and the callee's own block expands it.
                    reference = '{}.{}()'.format(
                        callee.module.rsplit('.', 1)[-1], callee.qualname
                    )
                    if not any(c.label == reference for c in node.children):
                        node.children.append(Node(label=reference))
                    continue
                if any(c.func is callee for c in node.children):
                    continue
                if callee.role == TRIVIAL:
                    # Collapsing the row must not lose what the helper touches.
                    # `_parse_args` is not worth a line, but the fact that this
                    # flow reaches argparse is worth keeping, so the helper's
                    # brackets move up onto the collapsed row.
                    if callee.name not in trivial:
                        trivial.append(callee.name)
                        for _, label in graph.externals.get(callee.node_id, []):
                            if label not in trivial_labels:
                                trivial_labels.append(label)
                    continue
                if (
                    drop_skim
                    and callee.role == SKIM
                    and not graph.callees(callee.node_id)
                ):
                    continue
                if callee.node_id in emitted:
                    node.children.append(
                        Node(
                            label=callee.qualname,
                            func=callee,
                            ret=callee.returns,
                            marker=_marker_for(callee),
                            repeat=True,
                        )
                    )
                    continue
                node.children.append(expand(callee, depth + 1, path | {func.node_id}))
            elif call.kind == PROJECT and call.label:
                label = '{}()'.format(call.label)
                if not any(c.label == label for c in node.children):
                    node.children.append(Node(label=label))
            elif call.kind == EXTERNAL and call.label and depth < external_depth:
                display = '{}()'.format(external_display(call))
                if not any(c.label == display and c.bracket for c in node.children):
                    node.children.append(Node(label=display, bracket=call.label))

        if trivial:
            node.children.append(
                Node(
                    label='… {}'.format(', '.join(sorted(trivial)[:6])),
                    bracket=', '.join(trivial_labels[:3]) or None,
                )
            )
        return node

    return expand(root, 0, set())


def _note_for(func: Func, mode: str) -> Optional[str]:
    """Whether this function's note survives the current budget rung."""
    if not func.note or mode == 'none':
        return None
    if mode == 'spine' and func.role != SPINE:
        return None
    return func.note


def _marker_for(func: Func) -> str:
    if func.role == SPINE:
        return '★'
    if func.role == SKIM:
        return '~'
    return ''


def _fit(
    roots: Sequence[Func],
    project: Project,
    graph: Graph,
    max_lines: int,
    members: Optional[Set[str]] = None,
) -> List[Node]:
    """Expand roots into trees, pruning down a ladder until they fit.

    The rungs go from cheapest concession to dearest, so a map only pays for
    the constraint it actually hits:

    1. keep everything
    2. drop skimmable leaves, which by definition hold no branching
    3. cap the depth, progressively — deep rows are the least useful, since a
       reader four levels down has left the flow the map is describing
    4. hide externals below the second level, keeping the surface visible at
       the top where it says what the module talks to
    5. drop the lowest-scoring root trees entirely

    Something always comes back. If even one root over budget, that is what
    ships, because a map that is four lines too long is a worse failure than
    no map at all only in a spec.
    """
    attempt: List[Node] = []
    for rung in _rungs():
        emitted: Set[str] = set()
        attempt = [
            _build_tree(root, project, graph, emitted=emitted, members=members, **rung)
            for root in roots
        ]
        if sum(n.line_count() for n in attempt) <= max_lines:
            return attempt
        # The last rung is free once the trees exist: roots are already in
        # score order, so taking the prefix that fits drops the least
        # interesting flows without rebuilding anything. Rebuilding once per
        # root count is what made this quadratic, and on a package the size of
        # asyncio it cost twenty-odd seconds.
        trimmed = _prefix_within(attempt, max_lines)
        if trimmed:
            return trimmed
    return attempt[:1]


def _prefix_within(nodes: Sequence[Node], max_lines: int) -> List[Node]:
    """The longest run of leading trees whose combined length fits."""
    total = 0
    kept: List[Node] = []
    for node in nodes:
        length = node.line_count()
        if total + length > max_lines:
            break
        total += length
        kept.append(node)
    return kept


def plan(project: Project, graph: Graph, max_lines: int = 40) -> Plan:
    """Build the whole map structure, splitting if it will not fit.

    The ladder is: full tree, then drop skimmable leaves, then cap the depth
    progressively, then hide externals below the second level. Whatever comes
    out of the bottom of that still over budget gets split instead — one block
    per module when there is more than one, otherwise one block per entry
    point.
    """
    entries = annotate(project, graph)
    spine = [f for f in project.funcs() if f.role == SPINE]
    spine.sort(key=lambda f: (f.depth if f.depth is not None else 99, -f.score))
    result = Plan(strategy='single', spine=spine, entries=entries)

    roots = _roots_for(entries, project, graph)
    if _wants_module_split(project):
        result.strategy = 'module'
        result.blocks = _module_blocks(project, graph, max_lines)
        with_funcs = sum(1 for m in project.modules.values() if m.funcs)
        result.omitted_modules = max(with_funcs - len(result.blocks), 0)
        return result

    nodes = _fit(roots, project, graph, max_lines)
    if sum(n.line_count() for n in nodes) <= max_lines:
        # A single-block map has no `##` heading, so this block's title and
        # purpose are never rendered — `render._heading` owns the document
        # heading and is the only thing that applies the purpose-provenance
        # rule. Filling them in here meant picking an arbitrary module out of
        # a dict and calling its docstring the whole map's purpose, which was
        # invisible only because nothing read it back.
        result.blocks = [Block(title='', purpose=None, roots=nodes)]
        return result

    result.strategy = 'module' if len(project.modules) > 1 else 'entry'
    result.blocks = (
        _module_blocks(project, graph, max_lines)
        if result.strategy == 'module'
        else _entry_blocks(project, graph, roots, max_lines)
    )
    if result.strategy == 'module':
        with_funcs = sum(1 for m in project.modules.values() if m.funcs)
        result.omitted_modules = max(with_funcs - len(result.blocks), 0)
    return result


# Below this, a package reads better as one tree: the flow across two files is
# the thing worth seeing, and splitting it hides the only edge that matters.
# At three or more, per-module blocks win — each carries its own docstring as a
# purpose line, and the flat tree would have thrown all of them away to show a
# single spine the reader cannot navigate by.
_SPLIT_MODULE_COUNT = 3


def _wants_module_split(project: Project) -> bool:
    """Whether to split by module before even trying to fit one tree."""
    return sum(1 for m in project.modules.values() if m.funcs) >= _SPLIT_MODULE_COUNT


def _roots_for(entries: Sequence[Func], project: Project, graph: Graph) -> List[Func]:
    """Tree roots for a single-block map: the entries, or the best guess."""
    if entries:
        return list(entries[:4])
    funcs = project.funcs()
    if not funcs:
        return []
    return [max(funcs, key=lambda f: f.score)]


def _module_blocks(
    project: Project, graph: Graph, max_lines: int, max_blocks: int = 8
) -> List[Block]:
    """One block per module, leaves first, capped at what a reader will read.

    Past eight blocks the document stops being a map and becomes a listing, so
    a large package is cut to the modules carrying the highest-scoring code.
    The survivors are then put back into dependency order, because the cut is
    about which modules matter and the order is about how to read them.

    The count of what was dropped is reported rather than hidden — a reader who
    knows they are seeing eight modules of thirty can go and ask for the rest.
    """
    blocks: List[Block] = []
    chosen = _select_modules(project, max_blocks)
    titles = _block_titles([project.modules[n].path for n in chosen])
    for name in chosen:
        module = project.modules[name]
        if not module.funcs:
            continue
        members = {f.node_id for f in module.funcs}
        _ensure_block_spine(module.funcs)
        roots = _module_roots(module, graph)
        # Each block is deliberately self-contained: a function shown in an
        # earlier block is still shown here, because a reader who jumps to one
        # module's block should not find its tree missing rows that happen to
        # have been spent elsewhere.
        nodes = _fit(roots, project, graph, max_lines, members=members)
        blocks.append(
            Block(
                title=titles[module.path],
                purpose=module.doc or module.header_comment,
                roots=nodes,
            )
        )
    return blocks


def _ensure_block_spine(funcs: Sequence[Func]) -> None:
    """Star the best function in a block that has none.

    A block is a map in its own right, and one with no star tells the reader
    to start anywhere. The overall spine list stays capped separately, so this
    only affects the markers inside the fence.
    """
    candidates = [f for f in funcs if f.role != TRIVIAL]
    if not candidates or any(f.role == SPINE for f in candidates):
        return
    max(candidates, key=lambda f: (f.score, -f.lineno)).role = SPINE


def _block_titles(paths: Sequence[str]) -> Dict[str, str]:
    """Name each block by the shortest path suffix that is unique among them.

    A basename alone is usually right and occasionally ambiguous. Flask has
    `flask/app.py` and `flask/sansio/app.py`, and a map with two blocks both
    headed `app.py` is asking the reader to guess which is which — the one
    question a heading exists to answer.

    Only the blocks in this map are considered, so a name stays short unless
    something it is actually shown beside forces it longer.
    """
    titles: Dict[str, str] = {}
    for path in paths:
        parts = path.split('/')
        for depth in range(1, len(parts) + 1):
            candidate = '/'.join(parts[-depth:])
            clash = any(
                other != path and other.endswith('/' + candidate) for other in paths
            )
            if not clash:
                titles[path] = candidate
                break
        else:
            titles[path] = path
    return titles


def _is_test_module(module) -> bool:
    """Whether a module is a test suite rather than the thing under test."""
    name = module.path.rsplit('/', 1)[-1]
    return (
        name.startswith('test_')
        or name.endswith('_test.py')
        or '/tests/' in module.path
        or '/test/' in module.path
    )


def _select_modules(project: Project, max_blocks: int) -> List[str]:
    """Which modules get a block, in the order they should be read.

    Tests are ranked below source when the slots run out. They are kept in the
    walk on purpose — a test suite is often the clearest statement of what code
    is for — but a project with three modules and three test modules should not
    spend half its map on the tests. Pointed at a test directory, where tests
    are all there is, nothing is deprioritised and they fill the map as they
    should.
    """
    order = [n for n in _module_order(project) if project.modules[n].funcs]
    if len(order) <= max_blocks:
        return order
    has_source = any(not _is_test_module(project.modules[n]) for n in order)
    ranked = sorted(
        order,
        key=lambda n: (
            has_source and _is_test_module(project.modules[n]),
            -max(f.score for f in project.modules[n].funcs),
        ),
    )
    keep = set(ranked[:max_blocks])
    return [n for n in order if n in keep]


def _module_roots(module, graph: Graph) -> List[Func]:
    """Within one module, the functions nothing else in that module calls.

    Trivial functions are filtered out even though they qualify. A module full
    of `@property` accessors has a dozen uncalled one-liners, and every one of
    them is a graph root; listing them buries whatever the module is actually
    for under its own boilerplate. They come back only if the filter would
    leave the block empty, which happens for pure record modules where the
    accessors genuinely are the content.
    """
    internal = set()
    for func in module.funcs:
        for callee in graph.callees(func.node_id):
            internal.add(callee)
    roots = [f for f in module.funcs if f.node_id not in internal]
    substantial = [f for f in roots if f.role != TRIVIAL]
    chosen = substantial or roots
    chosen.sort(key=lambda f: (-f.score, f.lineno))

    # Being uncalled is what makes something a way in, but it is not what
    # makes it worth reading, and in a class-heavy module the two come apart
    # badly. Having callers disqualifies you, which leaves the constructors
    # and the thin public wrappers as roots while the code doing the work sits
    # one level down and can never be one.
    #
    # httpx is the case. `Client.send` outscores `Client.__init__` by a
    # distance and has two internal callers, so the block led with two
    # constructors and the reader never met the function the module exists
    # for. The module's best-scoring function is promoted when nothing else
    # would have put it near the top.
    best = _best_in(module.funcs)
    if best is not None and best not in chosen[:2]:
        chosen.insert(0, best)

    return chosen or sorted(module.funcs, key=lambda f: f.lineno)[:1]


def _best_in(funcs: Sequence[Func]) -> Optional[Func]:
    """The function in a module most worth reading, trivia excluded."""
    candidates = [f for f in funcs if f.role != TRIVIAL]
    return max(candidates, key=lambda f: (f.score, -f.lineno)) if candidates else None


def _entry_blocks(
    project: Project, graph: Graph, roots: Sequence[Func], max_lines: int
) -> List[Block]:
    """One block per top-level flow, for a single file too big for one tree."""
    blocks: List[Block] = []
    for root in roots:
        emitted: Set[str] = set()
        node = _build_tree(root, project, graph, 4, emitted)
        blocks.append(
            Block(
                title='{}() flow'.format(root.qualname),
                purpose=root.doc,
                roots=[node],
            )
        )
    return blocks
